//Get all books
GET http://localhost:5000/api/book

###

//create a book
POST  https://book-inv-be.onrender.com/api/book
content-type: application/json

{
  "name": "Pride and Prejudice",
  "image": "https://images-na.ssl-images-amazon.com/images/I/51FcIOwvKdL._SX331_BO1,204,203,200_.jpg",
  "category": "romance",
  "code": 567890,
  "description": "Pride and Prejudice is a novel by Jane Austen. Set in the early 19th century, it follows the story of Elizabeth Bennet as she navigates issues of love, marriage, and social status.",
  "price": {
    "price": 14,
    "tax": 0.7,
    "discount": 0.25
  },
  "stock": {
    "unit": "piece",
    "quantity": 90,
    "date": "2022-09-02",
    "enableLowStockAlert": true,
    "lowStockAlertQuantity": 9
  }
}



//Generate another book


###
DELETE http://localhost:5000/api/book/646fe9e7b58f7be6d7d2d1c8